<?php
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Middleware\RoleMiddleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// Regular Home route
Route::get('/', function () {
    return view('index'); // Or your frontend page
});

// Auth routes (generated by Laravel Breeze or Jetstream)
Auth::routes();

// Admin Routes (restricted to users with 'admin' role only)
Route::middleware([RoleMiddleware::class])->prefix('admin')->group(function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('admin.dashboard');
});

// Regular User Route (Home Page)
Route::get('/home', [HomeController::class, 'index'])->name('home');
